#!/usr/bin/env bun
/**
 * migrate-v4.mjs — one-shot migration from structure v3 → v4 (user directive, 2026-09-03).
 *
 * v3:  books/<subject>/raw/<BATCH>/NNNN.jpg  +  books/<subject>/<part>/page-NNN.md
 * v4:  Books/Raw/<Subject>/<Original-Chapter-Name>/NNNN.jpg          (original chapter names)
 *      Books/Formatted/<Subject>/Chapter-NN-<Title>/page-NNN.md      (uniform numbered chapters)
 *      Books/Digital/<Subject>/Chapter-NN-<Title>/page-NNN.html      (HTML test edition, generated
 *                                                                    separately by generate-digital.mjs)
 *
 * What this script does (idempotent-safe by early exits):
 *   1. Moves all raw images     books/<subject>/raw/<BATCH>/      → Books/Raw/<Subject>/<rawName>/
 *   2. Moves all markdown pages books/<subject>/<part>/page-NNN.md → Books/Formatted/<subject>/<newName>/
 *   3. Rewrites in every page:  chapter_folder: <v3 value>        → <v4 folder name>
 *                               ../raw/<BATCH>/NNNN.jpg           → ../../../Raw/<Subject>/<rawName>/NNNN.jpg
 *                               (frontmatter `source_image:` + body scan-link line; expects exactly 2 occurrences)
 *   4. Verifies byte-integrity: new file == git HEAD old file with the same rewrites applied
 *   5. Removes the old books/ tree (book.json/chapter.json are regenerated by build-metadata.mjs)
 *
 * Run from repo root:  bun tools/migrate-v4.mjs
 */

import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const ROOT = process.cwd();
if (path.basename(ROOT) !== 'STUDY') die(`run from the STUDY repo root (cwd=${ROOT})`);

/**
 * Batch registry — batch code is the permanent join key between Raw / Formatted / Digital.
 * NOTE: book folders are TitleCase (Books/{Raw,Formatted,Digital}/Mathematics|Statistics);
 * the frontmatter `subject:` field stays a lowercase identifier (mathematics|statistics).
 */
const BATCHES = [
  { batch: 'M-0', subject: 'mathematics', subjectDir: 'Mathematics', rawName: 'Front-Matter',                  oldFolder: 'front-matter',                    newFolder: 'Chapter-00-Front-Matter',         kind: 'front-matter' },
  { batch: 'M-1', subject: 'mathematics', subjectDir: 'Mathematics', rawName: 'Unit-01-Functions-and-Graphs',  oldFolder: 'chapter-01-functions-and-graphs', newFolder: 'Chapter-01-Functions-and-Graphs', kind: 'chapter' },
  { batch: 'S-0', subject: 'statistics',  subjectDir: 'Statistics',  rawName: 'Front-Matter',                  oldFolder: 'front-matter',                    newFolder: 'Chapter-00-Front-Matter',         kind: 'front-matter' },
  { batch: 'S-1', subject: 'statistics',  subjectDir: 'Statistics',  rawName: 'Chapter-08-Set-Theory',         oldFolder: 'chapter-08-set-theory',           newFolder: 'Chapter-08-Set-Theory',           kind: 'chapter' },
  { batch: 'S-2', subject: 'statistics',  subjectDir: 'Statistics',  rawName: 'Chapter-09-Probability',        oldFolder: 'chapter-09-probability',          newFolder: 'Chapter-09-Probability',          kind: 'chapter' },
];

const problems = [];
function die(msg) { console.error('FATAL:', msg); process.exit(1); }
function problem(msg) { problems.push(msg); console.error('  ⚠ ' + msg); }

// ---------------------------------------------------------------------------
// 0. Preconditions
// ---------------------------------------------------------------------------
if (fs.existsSync(path.join(ROOT, 'Books'))) die('Books/ already exists — refusing to run twice.');
if (!fs.existsSync(path.join(ROOT, 'books'))) die('books/ tree not found — nothing to migrate.');
for (const b of BATCHES) {
  const src = path.join(ROOT, 'books', b.subject, 'raw', b.batch);
  const pages = path.join(ROOT, 'books', b.subject, b.oldFolder);
  if (!fs.existsSync(src)) die(`missing raw dir: ${src}`);
  if (!fs.existsSync(pages)) die(`missing page dir: ${pages}`);
}

// ---------------------------------------------------------------------------
// 1. Move raw images
// ---------------------------------------------------------------------------
console.log('== Moving raw images ==');
for (const b of BATCHES) {
  const src = path.join(ROOT, 'books', b.subject, 'raw', b.batch);
  const dst = path.join(ROOT, 'Books', 'Raw', b.subjectDir, b.rawName);
  fs.mkdirSync(dst, { recursive: true });
  const imgs = fs.readdirSync(src).filter(f => /\.(jpe?g|png)$/i.test(f)).sort();
  for (const f of imgs) fs.renameSync(path.join(src, f), path.join(dst, f));
  const after = fs.readdirSync(dst).filter(f => /\.(jpe?g|png)$/i.test(f)).length;
  if (after !== imgs.length) problem(`${b.batch}: expected ${imgs.length} images in ${dst}, found ${after}`);
  console.log(`  ${b.batch}: ${imgs.length} images → Books/Raw/${b.subject}/${b.rawName}/`);
}

// ---------------------------------------------------------------------------
// 2+3. Move markdown pages and rewrite paths
// ---------------------------------------------------------------------------
function rewriteV3toV4(text, b) {
  let out = text;
  // chapter_folder line (exact, single occurrence expected)
  const cfOld = `chapter_folder: ${b.oldFolder}`;
  const cfNew = `chapter_folder: ${b.newFolder}`;
  if (!out.includes(cfOld)) problem(`${b.batch}: chapter_folder line "${cfOld}" not found`);
  out = out.split(cfOld).join(cfNew);
  // raw paths (frontmatter source_image + body scan link; exactly 2 expected)
  const rawOld = `../raw/${b.batch}/`;
  const rawNew = `../../../Raw/${b.subjectDir}/${b.rawName}/`;
  const n = out.split(rawOld).length - 1;
  if (n !== 2) problem(`${b.batch}: expected 2 occurrences of "${rawOld}", found ${n}`);
  out = out.split(rawOld).join(rawNew);
  return out;
}

console.log('\n== Moving markdown pages + rewriting paths ==');
for (const b of BATCHES) {
  const srcDir = path.join(ROOT, 'books', b.subject, b.oldFolder);
  const dstDir = path.join(ROOT, 'Books', 'Formatted', b.subjectDir, b.newFolder);
  fs.mkdirSync(dstDir, { recursive: true });
  const pages = fs.readdirSync(srcDir).filter(f => /^page-\d{3}\.md$/.test(f)).sort();
  for (const f of pages) {
    const oldRel = path.posix.join('books', b.subject, b.oldFolder, f);
    const headText = execFileSync('git', ['show', `HEAD:${oldRel}`], { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
    const srcText = fs.readFileSync(path.join(srcDir, f), 'utf8');
    if (srcText !== headText) problem(`${oldRel}: worktree differs from git HEAD — migrating worktree version`);
    const newText = rewriteV3toV4(srcText, b);
    const expected = rewriteV3toV4(headText, b);
    if (newText !== expected) problem(`${oldRel}: post-rewrite content != HEAD-with-rewrites (unexpected drift)`);
    fs.writeFileSync(path.join(dstDir, f), newText);
    fs.unlinkSync(path.join(srcDir, f)); // remove the old copy (verified above before writing)
  }
  const after = fs.readdirSync(dstDir).filter(f => /^page-\d{3}\.md$/.test(f)).length;
  if (after !== pages.length) problem(`${b.batch}: expected ${pages.length} pages in ${dstDir}, found ${after}`);
  console.log(`  ${b.batch}: ${pages.length} pages → Books/Formatted/${b.subjectDir}/${b.newFolder}/ (paths rewritten, ${problems.length === 0 ? 'clean' : problems.length + ' problems so far'})`);
}

// ---------------------------------------------------------------------------
// 4. Remove old books/ tree (only generated book.json/chapter.json should remain inside)
// ---------------------------------------------------------------------------
console.log('\n== Removing old books/ tree ==');
const leftovers = [];
(function walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else leftovers.push(path.relative(ROOT, p));
  }
})(path.join(ROOT, 'books'));
console.log(`  leftover files (must all be generated JSON): ${leftovers.join(', ') || '(none)'}`);
for (const l of leftovers) if (!l.endsWith('book.json') && !l.endsWith('chapter.json')) problem(`unexpected leftover: ${l}`);
fs.rmSync(path.join(ROOT, 'books'), { recursive: true, force: true });

// ---------------------------------------------------------------------------
// 5. Final sweep: no stale references anywhere in the new tree
// ---------------------------------------------------------------------------
console.log('\n== Final sweep ==');
let mdCount = 0, imgCount = 0;
(function walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else {
      const rel = path.relative(ROOT, p);
      if (/\.md$/.test(e.name)) { mdCount++; }
      if (/\.(jpe?g|png)$/i.test(e.name)) { imgCount++; }
      if (/\.md$/.test(e.name)) {
        const t = fs.readFileSync(p, 'utf8');
        if (t.includes('../raw/')) problem(`${rel}: still contains "../raw/"`);
        if (/books\//.test(t)) problem(`${rel}: still contains "books/" path`);
      }
    }
  }
})(path.join(ROOT, 'Books'));

console.log(`  Books/ now holds ${mdCount} markdown pages, ${imgCount} raw images`);

if (mdCount !== 112) problem(`expected 112 markdown pages, found ${mdCount}`);
if (imgCount !== 112) problem(`expected 112 raw images, found ${imgCount}`);

console.log('\n=== migrate-v4 summary ===');
if (problems.length) { problems.forEach(p => console.log(' ⚠ ' + p)); console.log('PROBLEMS ❌'); process.exit(1); }
console.log('112/112 pages migrated, 112/112 images relocated, all rewrites verified against git HEAD. OK ✅');
console.log('Next: bun tools/build-metadata.mjs  →  bun tools/generate-digital.mjs');
